### ISSUE TITLE
json rpc 发送交易失败

### ISSUE THREAD

**Issue by fangdengfu** [FISCO-BCOS/whitepaper#1]
生成并启动创世节点时报错。
```
---------- Generate node genesis file ----------
RUN: bash generate_genesis.sh -d /home/fang/mydata/node0 -o /home/fang/mydata/node0 
God account address: 0xf78451eb46e20bc5336e279c52bda3a3e92c09b6
/home/fang/mydata/node0/genesis.json is generated
SUCCESS execution of command: bash generate_genesis.sh -d /home/fang/mydata/node0 -o /home/fang/mydata/node0 
---------- Deploy system contract ----------
RUN: bash deploy_systemcontract.sh -d /home/fang/mydata/node0 
Pre-start genesis node
Deploy System Contract
Start depoly system contract
RUN: babel-node deploy_systemcontract.js /home/fang/mydata/FISCO-BCOS/tools/web3lib/tmp_config_deploy_system_contract.js
SystemProxycomplie success！

## 报错内容
send transaction failed！ Error: Invalid JSON RPC response: "Error: connect ECONNREFUSED 127.0.0.1:8545\n    at Object.exports._errnoException (util.js:1020:11)\n    at exports._exceptionWithHostPort (util.js:1043:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)"
    at Object.InvalidResponse (/home/fang/mydata/FISCO-BCOS/tools/systemcontract/node_modules/_web3@0.17.0-beta@web3/lib/web3/errors.js:35:16)
    at request.onreadystatechange (/home/fang/mydata/FISCO-BCOS/tools/systemcontract/node_modules/_web3@0.17.0-beta@web3/lib/web3/httpprovider.js:107:32)
    at dispatchEvent (/home/fang/mydata/FISCO-BCOS/tools/systemcontract/node_modules/_xmlhttprequest@1.8.0@xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/home/fang/mydata/FISCO-BCOS/tools/systemcontract/node_modules/_xmlhttprequest@1.8.0@xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at handleError (/home/fang/mydata/FISCO-BCOS/tools/systemcontract/node_modules/_xmlhttprequest@1.8.0@xmlhttprequest/lib/XMLHttpRequest.js:532:5)
    at ClientRequest.errorHandler (/home/fang/mydata/FISCO-BCOS/tools/systemcontract/node_modules/_xmlhttprequest@1.8.0@xmlhttprequest/lib/XMLHttpRequest.js:459:14)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:314:9)
    at emitOne (events.js:96:13)

SUCCESS execution of command: babel-node deploy_systemcontract.js /home/fang/mydata/FISCO-BCOS/tools/web3lib/tmp_config_deploy_system_contract.js
/home/fang/mydata/FISCO-BCOS/tools/scripts
Stop genesis node
kill -9 
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
kill -9 
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
/home/fang/mydata/FISCO-BCOS/tools/scripts
Error: System Contract deploy failed.
Usage:
    -d  <genesis node dir>   Genesis node dir of the blockchain
```

**Comment by fangdengfu** [comment]
```
send transaction failed！ Error: Invalid JSON RPC response: "Error: connect ECONNREFUSED 127.0.0.1:8545\n at Object.exports._errnoException (util.js:1020:11)\n at exports._exceptionWithHostPort (util.js:1043:20)\n at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)"
at Object.InvalidResponse (/home/fang/mydata/FISCO-BCOS/tools/systemcontract/node_modules/_web3@0.17.0-beta@web3/lib/web3/errors.js:35:16)
at request.onreadystatechange (/home/fang/mydata/FISCO-BCOS/tools/systemcontract/node_modules/_web3@0.17.0-beta@web3/lib/web3/httpprovider.js:107:32)
at dispatchEvent (/home/fang/mydata/FISCO-BCOS/tools/systemcontract/node_modules/_xmlhttprequest@1.8.0@xmlhttprequest/lib/XMLHttpRequest.js:591:25)
at setState (/home/fang/mydata/FISCO-BCOS/tools/systemcontract/node_modules/_xmlhttprequest@1.8.0@xmlhttprequest/lib/XMLHttpRequest.js:610:14)
at handleError (/home/fang/mydata/FISCO-BCOS/tools/systemcontract/node_modules/_xmlhttprequest@1.8.0@xmlhttprequest/lib/XMLHttpRequest.js:532:5)
at ClientRequest.errorHandler (/home/fang/mydata/FISCO-BCOS/tools/systemcontract/node_modules/_xmlhttprequest@1.8.0@xmlhttprequest/lib/XMLHttpRequest.js:459:14)
at emitOne (events.js:96:13)
at ClientRequest.emit (events.js:188:7)
at Socket.socketErrorListener (_http_client.js:314:9)
at emitOne (events.js:96:13)
```

**Comment by fangdengfu** [comment]
单独去启动node0节点，发现端口监听没起来

```
cd /mydata/node0
sudo bash start.sh
```

**Comment by zhenyu-whu** [comment]
这个问题怎么还么有解决呢？
